apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "jira.fullname" . }}
  labels:
{{ include "jira.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "jira.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "jira.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      initContainers:
        - name: chown-data-volume
          image: busybox
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["chown", "2:2", "-R", "/var/atlassian/jira"]
          volumeMounts:
          - name: data
            mountPath: /var/atlassian/jira
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: X_PROXY_NAME
              value: {{ .Values.jira.reverseProxyHost | quote }}
            - name: X_PROXY_PORT
              value: {{ .Values.jira.reverseProxyPort | quote }}
            - name: X_PROXY_SCHEME
              value: {{ .Values.jira.reverseProxyScheme | quote }}
            - name: JAVA_OPTS
              value: {{ printf "-Xmx%s -Xms%s %s %s" .Values.jira.javaHeapSize .Values.jira.javaHeapSize .Values.jira.javaMemoryOptions .Values.jira.javaOptions | quote }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 300
            periodSeconds: 15
            timeoutSeconds: 3
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 3
          volumeMounts:
            - name: data
              mountPath: /var/atlassian/jira
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
        - name: data
{{ toYaml .Values.dataVolume | indent 10}}
