apiVersion: v1
appVersion: "2.2"
description: Treafik v2.2 helm chart 
name: traefik
version: 0.2.3
icon: https://raw.githubusercontent.com/containous/traefik/master/docs/content/assets/img/traefik.logo.png
home: https://traefik.io/
